// Script to add database fields to remaining Rangareddy medium-term crops
const fs = require('fs');

// Read the current cropData.ts file
const cropDataPath = 'c:/Users/ajith/OneDrive/Desktop/farmsphere-visions-main/frontend/src/data/cropData.ts';
let content = fs.readFileSync(cropDataPath, 'utf8');

// Database fields to add for each crop type
const databaseFields = {
  'Sugarcane': {
    supplyStatus: "High",
    originalDemandStatus: "Very High", 
    riskFactors: "Borers, red rot diseases",
    cropDuration: "10 months",
    primarySoilType: "Clay loam well-drained",
    waterRequirement: "High",
    climateSuitability: "20-35°C, 1000-1500mm rainfall",
    irrigationCompatibility: "Drip irrigation",
    landAreaSuitability: "Large",
    mitigationStrategies: "Disease resistant varieties, proper drainage",
    cropType: "Cash crop",
    costBreakdown: "Setts 20000, Fertilizers 30000, Labor 25000, Irrigation 15000",
    priceRange: "₹8-12 per kg",
    yieldRange: "35000-45000 kg per acre",
    breakEvenTime: "8 months"
  },
  'Cotton': {
    supplyStatus: "Medium",
    originalDemandStatus: "High",
    riskFactors: "Bollworm, aphid attacks",
    cropDuration: "6 months", 
    primarySoilType: "Black cotton soil",
    waterRequirement: "Moderate",
    climateSuitability: "21-30°C, 500-800mm rainfall",
    irrigationCompatibility: "Supplemental irrigation",
    landAreaSuitability: "Medium",
    mitigationStrategies: "Bt varieties, integrated pest management",
    cropType: "Fiber crop",
    costBreakdown: "Seeds 25000, Fertilizers 20000, Labor 25000, Pesticides 15000",
    priceRange: "₹45-55 per kg",
    yieldRange: "5000-7000 kg per acre",
    breakEvenTime: "5 months"
  },
  'Chilli': {
    supplyStatus: "Medium",
    originalDemandStatus: "High",
    riskFactors: "Thrips, mite infestation",
    cropDuration: "5 months",
    primarySoilType: "Sandy loam well-drained",
    waterRequirement: "Moderate",
    climateSuitability: "20-30°C, 600-1000mm rainfall",
    irrigationCompatibility: "Drip irrigation",
    landAreaSuitability: "Small to medium",
    mitigationStrategies: "Neem sprays, resistant varieties",
    cropType: "Vegetable",
    costBreakdown: "Seeds 15000, Fertilizers 20000, Labor 15000, Pesticides 10000",
    priceRange: "₹45-55 per kg",
    yieldRange: "4000-6000 kg per acre",
    breakEvenTime: "4 months"
  },
  'Tomato': {
    supplyStatus: "Medium",
    originalDemandStatus: "Very High",
    riskFactors: "Fruit borer, leaf miner",
    cropDuration: "4 months",
    primarySoilType: "Loamy well-drained",
    waterRequirement: "Moderate", 
    climateSuitability: "18-28°C, 600-1000mm rainfall",
    irrigationCompatibility: "Drip irrigation",
    landAreaSuitability: "Small to medium",
    mitigationStrategies: "Resistant varieties, crop rotation",
    cropType: "Vegetable",
    costBreakdown: "Seeds 12000, Fertilizers 18000, Labor 15000, Trellis 10000",
    priceRange: "₹20-30 per kg",
    yieldRange: "7000-9000 kg per acre",
    breakEvenTime: "3 months"
  },
  'Brinjal (Eggplant)': {
    supplyStatus: "Medium",
    originalDemandStatus: "High",
    riskFactors: "Fruit borer, shoot borer",
    cropDuration: "4 months",
    primarySoilType: "Sandy loam well-drained",
    waterRequirement: "Moderate",
    climateSuitability: "20-30°C, 600-1000mm rainfall",
    irrigationCompatibility: "Drip irrigation", 
    landAreaSuitability: "Small to medium",
    mitigationStrategies: "Netting, resistant varieties",
    cropType: "Vegetable",
    costBreakdown: "Seeds 10000, Fertilizers 15000, Labor 15000, Stakes 10000",
    priceRange: "₹25-35 per kg",
    yieldRange: "5000-7000 kg per acre",
    breakEvenTime: "3 months"
  },
  'Onion': {
    supplyStatus: "Medium",
    originalDemandStatus: "Very High",
    riskFactors: "Thrips, purple blotch",
    cropDuration: "5 months",
    primarySoilType: "Sandy loam well-drained",
    waterRequirement: "Moderate",
    climateSuitability: "15-25°C, 400-600mm rainfall",
    irrigationCompatibility: "Drip irrigation",
    landAreaSuitability: "Medium",
    mitigationStrategies: "Seed treatment, proper storage",
    cropType: "Vegetable",
    costBreakdown: "Seeds 15000, Fertilizers 20000, Labor 15000, Curing 10000",
    priceRange: "₹22-32 per kg",
    yieldRange: "7000-9000 kg per acre",
    breakEvenTime: "4 months"
  },
  'Coriander': {
    supplyStatus: "Medium",
    originalDemandStatus: "High",
    riskFactors: "Aphids, powdery mildew",
    cropDuration: "3 months",
    primarySoilType: "Sandy loam well-drained",
    waterRequirement: "Moderate",
    climateSuitability: "15-25°C, 400-800mm rainfall",
    irrigationCompatibility: "Drip irrigation",
    landAreaSuitability: "Small",
    mitigationStrategies: "Organic sprays, crop rotation",
    cropType: "Herb",
    costBreakdown: "Seeds 8000, Fertilizers 12000, Labor 12000, Irrigation 8000",
    priceRange: "₹45-55 per kg",
    yieldRange: "2500-3500 kg per acre",
    breakEvenTime: "2 months"
  },
  'Fenugreek': {
    supplyStatus: "Medium",
    originalDemandStatus: "High",
    riskFactors: "Aphids, powdery mildew",
    cropDuration: "3 months",
    primarySoilType: "Sandy loam well-drained",
    waterRequirement: "Moderate",
    climateSuitability: "15-25°C, 400-700mm rainfall",
    irrigationCompatibility: "Drip irrigation",
    landAreaSuitability: "Small",
    mitigationStrategies: "Disease resistant varieties",
    cropType: "Herb",
    costBreakdown: "Seeds 7000, Fertilizers 10000, Labor 10000, Irrigation 8000",
    priceRange: "₹40-56 per kg",
    yieldRange: "2000-3000 kg per acre",
    breakEvenTime: "2 months"
  },
  'Marigold': {
    supplyStatus: "Medium",
    originalDemandStatus: "High",
    riskFactors: "Aphids, spider mites",
    cropDuration: "3 months",
    primarySoilType: "Sandy loam well-drained",
    waterRequirement: "Moderate",
    climateSuitability: "15-30°C, 500-800mm rainfall",
    irrigationCompatibility: "Drip irrigation",
    landAreaSuitability: "Small",
    mitigationStrategies: "Neem sprays, companion planting",
    cropType: "Flower",
    costBreakdown: "Seeds 6000, Fertilizers 8000, Labor 10000, Irrigation 6000",
    priceRange: "₹45-55 per kg",
    yieldRange: "1500-2500 kg per acre",
    breakEvenTime: "2 months"
  },
  'Jasmine': {
    supplyStatus: "Medium",
    originalDemandStatus: "High",
    riskFactors: "Aphids, spider mites",
    cropDuration: "4 months",
    primarySoilType: "Sandy loam well-drained",
    waterRequirement: "Moderate",
    climateSuitability: "20-30°C, 600-1000mm rainfall",
    irrigationCompatibility: "Drip irrigation",
    landAreaSuitability: "Small",
    mitigationStrategies: "Regular pruning, shade management",
    cropType: "Flower",
    costBreakdown: "Plants 15000, Fertilizers 8000, Labor 8000, Trellis 4000",
    priceRange: "₹75-95 per kg",
    yieldRange: "1200-1800 kg per acre",
    breakEvenTime: "3 months"
  }
};

console.log('Database fields prepared for', Object.keys(databaseFields).length, 'crops');
console.log('Run this script with: node add_database_fields.js');
